import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:5173/', { waitUntil: 'networkidle' });
await page.waitForTimeout(3000);
const r = await page.evaluate(() => {
  const name = document.querySelector('h1');
  const fs = getComputedStyle(name).fontSize, fw = getComputedStyle(name).fontWeight;
  const c = document.createElement('canvas').getContext('2d');
  c.font = `${fw} ${fs} "Bricolage Grotesque Variable"`;
  const out = { fs, fw };
  for (const ch of ['H','E','m','i','Ş']) out[ch] = c.measureText(ch).actualBoundingBoxAscent.toFixed(1);
  const probe = document.querySelector('[data-probe]');
  const stage = probe.offsetParent;
  out.probeTop = probe.offsetTop; out.stageTop = stage.getBoundingClientRect().top; out.stageCls = stage.className;
  out.probeRect = probe.getBoundingClientRect().top;
  const E = document.querySelector('[data-char="E"]');
  out.Eoff = [E.offsetLeft, E.offsetTop, E.offsetParent.className];
  out.Erect = E.getBoundingClientRect().top;
  return out;
});
console.log(r);
await browser.close();
